### ISSUE TITLE
Is it possible to modify the target block time like clique?

### ISSUE THREAD

**Issue by eosclassicteam** [goerli/testnet#1]
cc @5chdn @holiman 

And I would like to also know the maximum TPS for aura engine

**Comment by 5chdn** [comment]
> Is it possible to modify the target block time like clique?

Yes, that's the "step duration".

> And I would like to also know the maximum TPS for aura engine

Over 9000 https://github.com/paritytech/parity-ethereum/issues/9393#issuecomment-418438868
