### ISSUE TITLE
Getting Görli ETH in bulk

### ISSUE THREAD

**Issue by lucas-janon** [goerli/testnet#104]
Hi!

We're building a multi-chain protocol that's highly dependent on liquidity pools on every chain, we'd like to get between 5000 and 10000 ETH in Görli to make sure that the pools are highly liquid.

Is it possible? Is there any procedure we need to follow?

Thank you.

**Comment by lucas-janon** [comment]
Here we go: `0x09b80BEcBe709Dd354b1363727514309d1Ac3C7b`

**Comment by envatic** [comment]
@q9f  Please send me Goerli ETH. 0x13DA09959d0CdDDB8CCEec41A0BfADaf5965bd24 There faucets are dry

**Comment by lucas-janon** [comment]
Hi @q9f!

We're hosting a [small multichain faucet](https://labs.zetachain.com/get-zeta) + [a bridge](https://labs.zetachain.com/swap) between Goerli and other chains like Mumbai, BSC Testnet and we get depleted pretty often. Is there any chance to get 50,000 gETH so we can keep the faucet alive for a few more months?

My address is still: `0x09b80BEcBe709Dd354b1363727514309d1Ac3C7b`.

Thank you.

**Comment by q9f** [comment]
Hi  @lucas-janon - I no longer serve Goerli requests. Please consider migrating to Sepolia.

**Comment by lucas-janon** [comment]
Hi @q9f, is it possible to get a big amount of ETH in Sepolia? If that's the case, I can chat about moving with the team.

**Comment by q9f** [comment]
Yes, we can do that!

**Comment by lucas-janon** [comment]
Nice. I'll chat with the team so we can integrate Sepolia into the protocol soon and will be back to you, thank you!

**Comment by ViniciusTenenteSecurrency** [comment]
Hey @q9f can you please provide me 10000 Sepolia ETH on 0x4C5F0f90a2D4b518aFba11E22AC9b8F6B031d204

I'm currently working on some projects that are really dependents of having ETH on some testnet so we can continue development.

Thank you!

**Comment by q9f** [comment]
Sent some!

**Comment by ViniciusTenenteSecurrency** [comment]
Thank you!

**Comment by lucas-janon** [comment]
> Nice. I'll chat with the team so we can integrate Sepolia into the protocol soon and will be back to you, thank you!

Hi again @q9f!

The protocol team is finally working on supporting Sepolia. Are bulk requests still possible? If that's the case, I'd like to get between 10 and 100k.

Thanks a lot!

**Comment by lucas-janon** [comment]
Hi @q9f!

I was wondering if you're still a Sepolia whale 😅 and can share some assets with me, ZetaChain is moving from Goerli to Sepolia and the broader team will need assets to support our operation.

My address is `0x09b80BEcBe709Dd354b1363727514309d1Ac3C7b`.

Thank you very much!
