### ISSUE TITLE
[Tools] One-way throttled bridge (faucet)

### ISSUE THREAD

**Issue by 5chdn** [goerli/testnet#13]
- [x] one-way from rinkeby
- [x] one-way from ropsten
- [x] one-way from kovan
- [x] throttled to X GöETH per Y time

**Comment by noot** [comment]
what sort of throttling do we want? 1 goeth per hour/day, 5 goeth per day, etc?

**Comment by ChainSafe** [comment]
Current plan is to allow a max of 100 testnet eth to be burned on each testnet. Allowing for a max of 300 Göeth per day per address.

**Comment by ChainSafe** [comment]
Currently just waiting on the UI to make this publicly available.
