### ISSUE TITLE
[Core] Clique engine for Trinity

### ISSUE THREAD

**Issue by 5chdn** [goerli/testnet#16]
- probably needs refactoring for additional engine
- ref https://github.com/ethereum/py-evm/issues/1457 https://github.com/ethereum/py-evm/pull/1299 https://github.com/ethereum/py-evm/issues/722
- and https://github.com/ethereum/py-evm/issues/1458 :hugs:

**Comment by 5chdn** [comment]
https://github.com/ethereum/trinity/issues/72

**Comment by soc1c** [comment]
https://github.com/ethereum/py-evm/pull/1855

**Comment by veox** [comment]
Initial implementation landed in Trinity: https://github.com/ethereum/trinity/pull/1196

No need to reopen anymore.
