### ISSUE TITLE
[Core] Clique engine for Aleth

### ISSUE THREAD

**Issue by 5chdn** [goerli/testnet#17]
- probably needs refactoring for additional engine
- ref https://github.com/ethereum/aleth/issues/5057

**Comment by lazaridiscom** [comment]
Is there any chance that this will get a bounty at some point? Especially the refactoring (= providing the means to easily add a new engine) would interest me much, both, architectural and code-level.

**Comment by 5chdn** [comment]
Yes. We are just waiting for the funds. Subscribe to this issue to get notified.

**Comment by soc1c** [comment]
ref https://github.com/ethereum/aleth/issues/5522

**Comment by chfast** [comment]
@chainsafeth @MPtherealMVP Can you put a Gitcoin bounty for it? We can help with integration and mentoring.

**Comment by soc1c** [comment]
we have very bad experience with gitcoin, especially with more complex tasks like that. it would be easier to find a developer willing to commit to this work first and then agree on a budget.

**Comment by chfast** [comment]
Ok. Who is suppose to look for the developer then?

**Comment by mariapaulafn** [comment]
Yo i’m gonna look for him/her/they! @chfast - will ping u tomorrow

**Comment by chfast** [comment]
Please put this request on hold until further notice.
