### ISSUE TITLE
[Tools] Open-source faucet

### ISSUE THREAD

**Issue by 5chdn** [goerli/testnet#18]

**Comment by karalabe** [comment]
The go-ethereum repo has a generic faucet that we deploy via puppeth for all private networks (https://github.com/ethereum/go-ethereum/tree/master/cmd/faucet). Same one running on https://faucet.rinkeby.io/ . If that's fine, this task can be covered already.

**Comment by 5chdn** [comment]
Yeah, that's amazing. We have one at https://faucet.goerli.mudit.blog/

And https://goerli-faucet.slock.it/ and https://bridge.goerli.com/
