### ISSUE TITLE
[Tools] Open-source block explorer

### ISSUE THREAD

**Issue by 5chdn** [goerli/testnet#19]
- placeholder ticket. we could also just use an existing one, e.g., blockscout.

**Comment by 5chdn** [comment]
https://github.com/poanetwork/blockscout/issues/1114

**Comment by ChainSafe** [comment]
blockscout.com/eth/goerli

**Comment by ChainSafe** [comment]
[Görli on blockscout](https://blockscout.com/eth/goerli)
