### ISSUE TITLE
[Comms] Görli Testnet Contributors Call #0

### ISSUE THREAD

**Issue by 5chdn** [goerli/testnet#23]
### Görli Testnet Contributors Call #0

Date / Time
- Friday, November 16th, 2018
- [9pm UTC](https://savvytime.com/converter/germany-berlin-to-canada-toronto-ca-san-francisco-china-shanghai/10pm)

Agenda
- Hello, world!
- Overview roadmap & milestones
  - Clique and Aura
  - Görli and Classic
  - Cores and Tools
- Progress current tasks
  - Website for Görli 
  - Testnet bridges
  - Görli to replace Ropsten
  - Görli Classic to replace Morden Classic
- Client updates
  - Parity Ethereum w/ Görli
  - Nethermind w/ Görli
- Discussion open issues
- Outlook

All contributors and volunteers invited. Join Gitter for invite: [gitter.im/goerli/testnet](https://gitter.im/goerli/testnet)

**Comment by ChainSafe** [comment]
@noot & @CFDevelopment will have a demo of the bridge and bridge UI!

**Comment by roninkaizen** [comment]
+1
=roninkaizen ;-)

**Comment by karalabe** [comment]
Here's a gift from the Geth team :) https://github.com/ethereum/go-ethereum/pull/18121

**Comment by karalabe** [comment]
Btw, just my 2c on "Görli to replace Ropsten". I don't think that's a wise decision. I think the "official" Ethereum test network should always try to mimic mainnet as much as possible, and most essentially use the same consensus mechanisms to detect issues before they have a chance to hit mainnet (e.g. difficulty adjustment consensus issue).

Having a PoA testnet **too**  for developers is fine. Wiping and relaunching a new PoW "official" testnet is also fine. Lets just not make the mistake of killing the primary testing point of Ethereum.

**Comment by egalano** [comment]
I'll be there! Is the plan forward for Kovan and Rinkeby going to be discussed or is that out of scope for this meeting? If Infura is going to add support for Goerli, it'd be great to be able to understand if we are committing to supporting a replacement for one of the existing testnets or an additional testnet.

**Comment by chrishobcroft** [comment]
Here is the recording of the livestream from the call: https://youtu.be/TWak0-Rnves

**Comment by ChainSafe** [comment]
Awesome, thank you!

**Comment by karalabe** [comment]
Ok, I've slept on it. I don't feel so strongly about a PoW testnet any more, as long as we make hard forks more strict and add an additional "private" PoW fork test before touching any testnet.

**Comment by 5chdn** [comment]
I mean, we don't have to kill the network. Technically, we can't kill it even. But if nobody keeps it alive, I'm not sad if Ropsten dies.

**Comment by roninkaizen** [comment]
i see it from a more practical "point"-
as there are enough people still willing to run ropsten the way,
they did "so far" us as community with the "newer" engine can only offer them to look around,
if that testing conditions are better or same ways "productive" as with with ropsten itself.

time will show which kind of structure will be kept up, cause running such systems/nodes can cost money if you do not use solar-panels on your own house. and one house is not a network ;-)

in this case the community of devs i have met are interested in an "not pure parity" PoA-Testnet
with pairing possibilites of geth and nethermind as well as pantheon.
a broad variety of client types made me join ethereum "ealier days"- 
why should this principle be changed while providing testnet-structures?

As long as it is a valid testplattform,  devs will use the clique engine to find about its inherent health and possibilities. 
More variety within a testnet is a win but not a must- 
we decide about it, while using a network to test. 
there is no win situation for ropsten for sure, neither for goerli-
it`s an approach and with goerli i see different possibilities of chain-structures now 
much more clear. 

at the end the networks will "co"exist as chains exist which needed to be tested and people are willing and able to run such structure "long-term" mostly uninterrupted.

**Comment by 5chdn** [comment]
Closing in favour of #33

**Comment by 5chdn** [comment]
**Recording**: https://www.youtube.com/watch?v=TWak0-Rnves
