### ISSUE TITLE
@chainsafe -> @chainsafeth

### ISSUE THREAD

**Issue by ligi** [goerli/testnet#26]
In the README and here: https://github.com/goerli/pm/blob/master/FINANCE.md

@chainsafe is not a valid twitter account. It is a valid github account though - but as in the same section @MPtherealMVP is mentioned - which is only a twitter account - I think chainsafeth should be used.

**Comment by ChainSafe** [comment]
fixed!

**Comment by ligi** [comment]
top! It is still wrong in the README of this repo though

**Comment by ChainSafe** [comment]
lol, I just noticed! Thanks!

**Comment by 5chdn** [comment]
Can we merge both repositories please?

**Comment by ChainSafe** [comment]
I prefer we make this the repo for technical discussions and pm (name to be changed) to be for non-technical (i.e. comms coordination, keeping our meeting notes together, linking towards external pages, finances, and a contributors list). However at the end of the day this is not very important (for the project and me), so if you really want the two to be merged I will do it tonight or early tomorrow, no problem at all.
