### ISSUE TITLE
[Tools] Devops tooling for testing PoA testnets locally

### ISSUE THREAD

**Issue by jwasinger** [goerli/testnet#27]
https://github.com/paritytech/parity-deploy is a great tool for testing parity locally under various consensus configurations.  However, it doesn't easily extend itself to using multiple clients.  It would be great if we had a tool that allowed us to specify:

 * consensus type
 * number of different clients
 * configuration of each client (e.g. is client a signer?)
 * ability to spin up other services such as etherscan

The output of this program would be configuration necessary to spin up a local network of docker containers.

**Comment by 5chdn** [comment]
- ref https://github.com/paritytech/parity-deploy/pull/82
- ref https://github.com/goerli/parity-goerli/pull/26

**Comment by 5chdn** [comment]
Considering this done
