### ISSUE TITLE
[Tools] Two-way throttled bridge (faucet)

### ISSUE THREAD

**Issue by ChainSafeSystems** [goerli/testnet#28]
- [ ] Integrate morden testnet etc
- [ ] Allow for any testnet eth to be swapped either way through the bridge
- [ ] Create a generic user interface to allow for the swapping of any testnet eth/etc
- [ ] Allow `m out of n` authority signatures for bridging 
- [ ] Allow for ETH to be locked for GöTH at a ratio of 1:1000

**Comment by noot** [comment]
I have started working on this :)

**Comment by 5chdn** [comment]
What about a bridge from ETH to Görli? Instead of burning, you could lock your ETH for 4 weeks to redeem testnet GöETH?

**Comment by noot** [comment]
@5chdn yes, I can do that as well.  what do you think is a good ratio of ETH to GöETH?

**Comment by 5chdn** [comment]
1:1000

**Comment by ChainSafe** [comment]
incredible idea @5chdn :+1:

**Comment by jvt2** [comment]
![piramids of giza](https://user-images.githubusercontent.com/16857788/52501015-519b9c80-2bad-11e9-9f8c-5f755666b62a.jpg)

**Comment by 5chdn** [comment]
Are we going to integrate this into bridge.goerli.com?

**Comment by noot** [comment]
@5chdn yeah we can do that! currently the one-way bridge is up there. changing it to two-way is just a matter of deploying new contracts, and likely small ui changes. when would should that be done?

**Comment by 5chdn** [comment]
I honestly think we are fine with the one-way bridges #13 

But if you want to work on the two-way bridges, just create your own timeline, as long as people can request GöETH this way.
