### ISSUE TITLE
[Core] Unit test cases for parity clique

### ISSUE THREAD

**Issue by jwasinger** [goerli/testnet#34]
Once we have the implementation working, we should start porting test cases from go-ethereum over (https://github.com/ethereum/go-ethereum/blob/master/consensus/clique/snapshot_test.go)

Also, we are bound to find consensus issues when we go live.  Fixes should be accompanied by unit tests that capture the edge cases we find.

**Comment by 5chdn** [comment]
Moved to https://github.com/goerli/parity-goerli/issues/36
