### ISSUE TITLE
[Comms] Görli Testnet Contributors Call #2 will be GÖRLICON 

### ISSUE THREAD

**Issue by 5chdn** [goerli/testnet#36]
# GörliCon

Save the date: **January 31, 2019**

Location: Berlin, Germany @ Factory Görlitzer Park
Agenda: TBA - please let me know if you want to host a talk or workshop

GörliCon Pariticipation Form https://docs.google.com/forms/d/e/1FAIpQLSeO8TD70L_KkW4Ont4tx1w_imvYisdbwl0u4fjx8hpfb3d2Aw/viewform

**Comment by 5chdn** [comment]
GörliCon Pariticipation Form https://docs.google.com/forms/d/e/1FAIpQLSeO8TD70L_KkW4Ont4tx1w_imvYisdbwl0u4fjx8hpfb3d2Aw/viewform

**Comment by 5chdn** [comment]
https://goerli.net/

RSVP https://kickback.events/event/0xe2d2c31c68626b6c1301a49ed50854e1cae0c8fa

**Comment by 5chdn** [comment]
That was fun :tada:

**Comment by 5chdn** [comment]
All videos: https://www.youtube.com/watch?v=d961TWOSnBU&list=PLjOcf_IVqERknYTwN0k1d5cwOd_LGhn3E

**Comment by roninkaizen** [comment]
yes it was fun,
nice to see so many goerlians :+1:
