### ISSUE TITLE
[TASK] Simplify/Refine/Document Goerli

### ISSUE THREAD

**Issue by lazaridiscom** [goerli/testnet#40]
(Continuation of https://github.com/goerli/parity-goerli/issues/50)

(what needs to be done next)

### Requirements

Requirements (for any results, be it in code, product, project, docu etc.):
* **easy to understand for IT professionals with not much Blockchain (BC) experience)**

The initial plan was to got only into the "parity-goerli" part. Yet it is essential that the overall material (Website, Product, Project etc.) gets a little bit "polished".

Starting with the most relevant:

### Code, Parity

**Simplify the Implementation of Additional Engines within Parity**

Start to "replay" the existent chunks of work (e.g. branches merged, PRs) to extract abstractions simplifications, e.g.:

* https://github.com/goerli/parity-goerli/pull/2
* Isolate code-changes which could be merged stand-alone
* Review the relevant Partiy Codebase in order to come up with potential simplifications
* direction (future) : modularized consensus-engine, low coupling to other modules.
* Provide at minimum one Parity-Eth code-level simplification example (either the solution or the specification)

In parallel to the above

* observe the ongoing work on parity-goerli
  * decide about how much time to invest for
    * the alternate plan (Task C)
    * the rework (= strict refactoring and slight redesign) of the parity-ethereum client.

### Product, Goerli

* Identify teach-in barriers, provide (or at least specify) solutions
* Provide basic documentation
* direction (future tasks): Goerli becomes a reference-point re "how testnets should be"

### Projects, Goerli

* Identify teach-in barriers, provide (or at least specify) solutions
* Provide basic documentation
* direction (future tasks): Goerli projects become a reference-point for "cross-client" test-net cooperation

### Budget

5K, the results will be available within 14 days (top, depending on necessary "digestion" breaks).

(limited scope budget, can be used as a foundation to judge for further extension. Seeing the goals of the Goerli and especially the Parity project, the estimated effort to refine all relevant systems goes into months.)

**Comment by 5chdn** [comment]
Hi @lazaridiscom - thanks for your proposal. I really appreciate your work here.

I updated the website and will double down on documentation. For the Parity implementation, I identified two potential candiates. Thanks for your contributions.
