### ISSUE TITLE
[SYNC] Synchronization issues 2019-02-03

### ISSUE THREAD

**Issue by lazaridiscom** [goerli/testnet#41]
As mentioned within:

[February 3, 2019 6:10 AM](https://gitter.im/goerli/testnet?at=5c5669a0ceb5a2264f85c43f)

(EDIT: a note to process: any upcoming issues should be filed here, instead of just being discussed/processed exclusively on a chat-medium like gitter. )

**Comment by 5chdn** [comment]
Please add some more details here. Also, it might be a Geth problem, so it's better to reopen the ticket for whatever client is affected.
