### ISSUE TITLE
[Tools] Enable Clique chain spec for Parity in Puppeth

### ISSUE THREAD

**Issue by 5chdn** [goerli/testnet#44]
Currently, puppeth does not allow clique chain specs.

Sample genesis versus chainspec: https://github.com/goerli/parity-goerli/commit/9dbe5b34593d1b0de3698d57f794b499452f42e2

**Comment by 5chdn** [comment]
ref https://github.com/ethereum/go-ethereum/pull/18172

**Comment by thefallentree** [comment]
I will do this

**Comment by thefallentree** [comment]
@5chdn  to clarify:  is the goal for this bug to generate an gensis.json for parity using puppeth ?

**Comment by 5chdn** [comment]
Yes. Puppeth already has this functionality, but it's disabled for Clique.
