### ISSUE TITLE
[Comms] Görli Testnet Contributors Call #4 "Istanbul"

### ISSUE THREAD

**Issue by soc1c** [goerli/testnet#60]
### Görli Testnet Contributors Call #4

Date / Time
- Tuesday, September 17th, 2019
- [12pm UTC](https://savvytime.com/converter/germany-berlin-to-canada-toronto-ca-san-francisco-china-shanghai/2pm)

Agenda
- Istanbul Hardfork Activation
  - Date/Time
  - Block number

All contributors and volunteers invited. Join Gitter for invite: [gitter.im/goerli/testnet](https://gitter.im/goerli/testnet)

cc @souptacular

---

scroll down for meeting minutes: https://github.com/goerli/testnet/issues/60#issuecomment-532200530

**Comment by soc1c** [comment]
I will propose block number `1561651` (12:00 pm UTC  |  Wednesday, October 30, 2019) for Görli Testnet. That is 6 weeks from now and well after Devcon 5.

**Comment by timbeiko** [comment]
IIRC, the goal was to have the upgrade on Oct 2nd, prior to devcon, for Goerli. (see previous [decision](https://github.com/ethereum/pm/blob/master/All%20Core%20Devs%20Meetings/Meeting%2070.md#decisions))

If we want to fork Goerli at the same time, then I would propose `1400041`, which should be around October 2nd.

**Comment by soc1c** [comment]
That's in two weeks. It will be a mess.

**Comment by roninkaizen** [comment]
i agree with soc1c; could we please discuss this tommorow during the call?
i am really willing and also interested in participating in testing 
or pre-testing in close correspondance with Thomasz from nethermind.

**Comment by tkstanczak** [comment]
is the call happening?

**Comment by soc1c** [comment]
yes in 5 min https://us04web.zoom.us/j/388590582

**Comment by soc1c** [comment]
- **Afri** welcomes everyone
  - Attendees: Adrian, Afri, Danno, Hudson, Tim, Tomasz, Vaibahv, Ronin
- **Hudson** starts with background on Istanbul planning and the testnet hardfork date Oct/2, 2019
  - Istanbul was estimated to hit mainnet in Oct
  - It was decided to have longer testnet testing phase though
  - It was decided to have testnet fork Oct/2
  - Görli has most clients, Ropsten has most traffic
  - No block number for any of the testnets proposed yet
  - all-core-devs assumed 2 weeks is enough for announcement
- **Tomasz** says Görli should not be the first testnet to fork
  - but in case everything goes well, it is also the best network to fork
  - actual state tests will come up after the actual hardfork
- **Hudson** previously suggested palindrome numbers for Ropsten and Görli
  - However, safety should be number 1 priority
  - Also there is Devcon 5 in Osaka coming up
- **Afri** explains his Oct/30 logic (Devcon)
  - two weeks is not enough to publish releases for all clients and ping all validators to upgrade
  - four weeks would be Devcon 5
  - six weeks is optimal as everyone is back from the conferences
- **Hudson** agrees it would be complicated before/during Devcon
  - But also sees some urgency and suggests to _just let it run_ during Devcon 
- **Hudsom** proposes Ropsten fork on Oct/2 and Görli on Oct/30
- **Tomasz** proposes bootstrapping a new Istanbul-only testnet
  - people were asking about it
  - Hudson approves this
  - Afri approves new testnet and Hudson's HF plans
  - Tomasz and Hudson agree with Oct/2 Ropsten fork and Oct/30 Görli fork
- **Adrian** asks whether clients are ready
  - Hudson says all major clients except for Aleth and Trinity merged Istanbul
- **Danno** (inaudible), discussing releases for Pantheon
- **Hudson** suggests to use `1561651` for Görli as Afri suggested
  - _general agreement_
- **Tomasz**: all clients needs releases
  - we need to start talking to all validators
- **Afri** _concludes_
- Bonus: **Afri** computes block time of 17.13 seconds on Ropsten and proposes `6485846` as fork block number for Ropsten Istanbul activation
  - goal should be doing one release for both testnets
  - Hudson will forward it to all-core-devs
- **Afri** again encourages to have one release for both testnets
- **Danno** discusses future course of action for hardforks
  - coordination between all-core-devs and Görli community
- **Afri** suggests a heads-up of at least 4 weeks for Görli hardforks
- **Adrian** kindly requests all validators to swap out the pantheon node for the new one:
    ```
    clique.propose("0x5dfe3772ceb73531357c3c747b6999cf59a59533", true)
    clique.propose("0x22ea9f6b28db76a7162054c05ed812deb2f519cd", false)
    ```
- _Bye!_
