### ISSUE TITLE
stats-server down?

### ISSUE THREAD

**Issue by roninkaizen** [goerli/testnet#61]
anyone else encountering the unavailability of both ethstats-servers 
stats.goerli.net
stats.goerli.kotti.net
and the goerli-net website?

**Comment by soc1c** [comment]
yeah we probably lost the domain

**Comment by roninkaizen** [comment]
as it seems to me, somebody has "cpatured" it,
i am trying to get it, but in case i am not succesful with it, 
i would prefer a dm to discuss, how to deal with this and 
how to resurrect the goerli-page somewhere else, now being aware of two duties, 
a goerlinator would have to care about.

**Comment by soc1c** [comment]
it's back online

**Comment by roninkaizen** [comment]
thank you very much soc1c!
