### ISSUE TITLE
New Kotti Commons Projects

### ISSUE THREAD

**Issue by gitr0n1n** [goerli/testnet#67]
Status Dashboard:
https://blockscout.com/etc/kotti/
https://kotti.etcnodes.org/
http://kotti.etcstats.org
http://kotti.etherstats.net
https://stats.kotti.goerli.net/
https://expedition.dev/?network=kotti

Block Explorer:
https://blockscout.com/etc/kotti/
http://kotti.ethereumtest.net
https://expedition.dev/?network=kotti

Faucets:
http://kottifaucet.me/
http://kotti.etherdrip.net

**Comment by soc1c** [comment]
Thanks 04f3881de3e6722ee902101fe8c42399213bd0ef
