### ISSUE TITLE
"Proof of Twitter" unavailable

### ISSUE THREAD

**Issue by ongrid** [goerli/testnet#72]
Wrong URL of "Proof of Twitter" links (here and in pm repos) or twit was removed by the author.

**Comment by roninkaizen** [comment]
d.o.n.e.

**Comment by roninkaizen** [comment]
i did close it, without mentioning why.
the twit-handle changed therefor-
is a new "Proof of Twitter" needed for any purpose?

**Comment by roninkaizen** [comment]
double
https://github.com/goerli/testnet/issues/70
