### ISSUE TITLE
hello, I would like to be a signer on the testnet

### ISSUE THREAD

**Issue by jordan69420** [goerli/testnet#73]
my address is 0x325EDA4dDcf09F3565E7b3A9344d6Ab85A43cDa9, can you authorize me

**Comment by roninkaizen** [comment]
please provide at least 4 weeks your logs that you continously run your node 
to proove somehow that you are really participating, maybe also explain what you intend to learn, realize or to test, as you like.

**Comment by q9f** [comment]
thank you for your interest. goerli currently does not look for new signers.
