### ISSUE TITLE
0x0000000000000000000000000000000000000000

### ISSUE THREAD

**Issue by DrZainAzm** [goerli/testnet#74]
{
	"compiler": {
		"version": "0.6.2+commit.bacdbe57"
	},
	"language": "Solidity",https://api-goerli.etherscan.io/api?module=contract&action=getsourcecode&address=0x0000000000000000000000000000000000000000&apikey=YourApiKeyToken
	"output": {
		"abi": [
			{
				"inputs": [],
				"name": "retrieve"

"outputs": [
					{
						"internalType": "uint256",https://api-goerli.etherscan.io/api?module=contract&action=getsourcecode&address=0x0000000000000000000000000000000000000000&apikey=YourApiKeyToken
						"name": "",
						"type": "uint256"
					}
				],
				"stateMutability": "view"

"sources": {
		"browser/1_Storage.sol": {
			"keccak256": "0x790c322296d253a536d03e4c549fb533187ef1c4d35f7c5c52a4ede2730fc214",
			"urls": [
				"bzz-raw://544b435f50c5790028e53848ae30a9d71005f60816b0a93483047bcd32904084",
				"dweb:/ipfs/QmSB24iAbTTSh4uCxx6hLzo2tSre95BEa5jxhLq4xJXQDg"
			]
		}
	},
	"version": 1
}

curl -i https://api.github.com/users/octocat/orgs HTTP/1.1 200 OK Server: nginx Date: Fri, 12 Oct 2012 23:33:14 GMT Content-Type: application/json; charset=utf-8 Connection: keep-alive Status: 200 OK ETag: "a000000000000000000000000000000" X-GitHub-Media-Type: github.v3 X-RateLimit-Limit: 5000 X-RateLimit-Remaining: 4987 X-RateLimit-Reset: 1350085394 Content-Length: 5 Cache-Control: max-age=0, private, must-revalidate X-Content-Type-Options: nosniff

from":"0x0000000000000000000000000000000000000000","contractAddress":"0xed5a231ecc0fa775980ad7b86e49872feacd4c8f","to":"0xc287cf1f50d5bd56de70bdec1f4103d2b733a6d4","value":"8400000000000000000000","tokenName":"LuckyBucks","tokenSymbol":"LBT","tokenDecimal":"18"

https://etherscan.io/address/0xed5a231ecc0fa775980ad7b86e49872feacd4c8f#writeContract

var Web3 = require('web3'); var web3 = new Web3(new Web3.providers.HttpProvider()); var version = web3.version.api; $.getJSON('https://api.etherscan.io/api?module=contract&action=getabi&address=0x0000000000000000000000000000000000000000', function (data) { var contractABI = ""; contractABI = JSON.parse(data.result); if (contractABI != ''){ var MyContract = web3.eth.contract(contractABI); var myContractInstance = MyContract.at("0x0000000000000000000000000000000000000000"); var result = myContractInstance.memberId("0xfe8ad7dd2f564a877cc23feea6c0a9cc2e783715"); console.log("result1 : " + result); var result = myContractInstance.members(1); console.log("result2 : " + result); } else { console.log("Error" ); } });

# get json from contract https://api.etherscan.io/api?module=contract&action=getabi&address=0x0000000000000000000000000000000000000000&apikey=xxx

Block #11298905 to #11298929 (Total of 11,298,930 blocks)

Showing uncle (#11298359 to #11298957) out of 1,088,860 total uncles

contract Test { function Test(){ b = 0x0000000000000000000000000000000; } event Event(uint indexed a, bytes32 b) event Event2(uint indexed a, bytes32 b) function foo(uint a) { Event(a, b); } bytes32 b; }

http://api.etherscan.io/api?module=contract&action=getabi&address

https://api.etherscan.io/api?module=account&action=txlistinternal&address=0xed5a231ecc0fa775980ad7b86e49872feacd4c8f&startblock=0&endblock=6919408&page=1&offset=10&sort=asc&apikey=YourApiKeyToken

{"status":"1","message":"OK-Missing/Invalid API Key, rate limit of 1/5sec applied","result":[{"blockNumber":"6919408","timeStamp":"1545289246","hash":"0x99167c2758e51d5539c3a23d54ff40a74da9ccac3ca2c01ec36f807a8c130a69","nonce":"0","blockHash":"0x6461e6134cbe64950365280560b62e7ddb66252e4081a8f29ab11308861972ac","transactionIndex":"145","from":"0x8c6f76e87d28bc8689cd76601668b99fbe35d11b","to":"","value":"0","gas":"1209061","gasPrice":"4000000000","isError":"0","txreceipt_status":"1","input":"0x608060405234801561001057600080fd5b5060008054600160a060020a0319163317905560408051808201909152600b8082527f4c75636b79204275636b7300000000000000000000000000000000000000000060209092019182526100679160069161014f565b506040805180820190915260038082527f4c4254000000000000000000000000000000000000000000000000000000000060209092019182526100ac9160079161014f565b5060088054601260ff19909116179081905560ff16600a0a633b9aca00026005819055733c5459bcde2d5c1edc4cc6c6547d6cb360ce5ae96000818152600360209081527fba3fc78e3930372fc6c5bf4ede134b3a0a3abdcb39c601efe840911f58632fac8490556040805194855251929391927fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef9281900390910190a36101ea565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f1061019057805160ff19168380011785556101bd565b828001600101855582156101bd579182015b828111156101bd5782518255916020019190600101906101a2565b506101c99291506101cd565b5090565b6101e791905b808211156101c957600081556001016101d3565b90565b610ed380620001fa6000396000f3fe608060405260043610610116577c0100000000000000000000000000000000000000000000000000000000600035046306fdde03811461011b578063095ea7b3146101a557806317ffc320146101f257806318160ddd1461022757806323b872dd1461024e5780632d06177a14610291578063313ce567146102c457806339509351146102ef57806340c10f19146103285780634e71e0c81461036157806370a082311461037657806382384e9a146103a95780638da5cb5b146103dc57806395d89b411461040d578063a457c2d714610422578063a9059cbb1461045b578063ac18de4314610494578063dd62ed3e146104c7578063e30c397814610502578063f2fde38b14610517578063ffdd5cf11461054a575b600080fd5b34801561012757600080fd5b5061013061057d565b6040805160208082528351818301528351919283929083019185019080838360005b8381101561016a578181015183820152602001610152565b50505050905090810190601f1680156101975780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b3480156101b157600080fd5b506101de600480360360408110156101c857600080fd5b50600160a060020a038135169060200135610613565b604080519115158252519081900360200190f35b3480156101fe57600080fd5b506102256004803603602081101561021557600080fd5b5035600160a060020a0316610691565b005b34801561023357600080fd5b5061023c6107db565b60408051918252519081900360200190f35b34801561025a57600080fd5b506101de6004803603606081101561027157600080fd5b50600160a060020a038135811691602081013590911690604001356107e1565b34801561029d57600080fd5b506101de600480360360208110156102b457600080fd5b5035600160a060020a03166108aa565b3480156102d057600080fd5b506102d9610962565b6040805160ff9092168252519081900360200190f35b3480156102fb57600080fd5b506101de6004803603604081101561031257600080fd5b50600160a060020a03813516906020013561096b565b34801561033457600080fd5b506101de6004803603604081101561034b57600080fd5b50600160a060020a038135169060200135610a1b565b34801561036d57600080fd5b50610225610a88565b34801561038257600080fd5b5061023c6004803603602081101561039957600080fd5b5035600160a060020a0316610b10565b3480156103b557600080fd5b506101de600480360360208110156103cc57600080fd5b5035600160a060020a0316610b2b565b3480156103e857600080fd5b506103f1610b40565b60408051600160a060020a039092168252519081900360200190f35b34801561041957600080fd5b50610130610b4f565b34801561042e57600080fd5b506101de6004803603604081101561044557600080fd5b50600160a060020a038135169060200135610bb0565b34801561046757600080fd5b506101de6004803603604081101561047e57600080fd5b50600160a060020a038135169060200135610bfb565b3480156104a057600080fd5b506101de600480360360208110156104b757600080fd5b5035600160a060020a0316610c08565b3480156104d357600080fd5b5061023c600480360360408110156104ea57600080fd5b50600160a060020a0381358116916020013516610c66565b34801561050e57600080fd5b506103f1610c91565b34801561052357600080fd5b506102256004803603602081101561053a57600080fd5b5035600160a060020a0316610ca0565b34801561055657600080fd5b506101de6004803603602081101561056d57600080fd5b5035600160a060020a0316610ce6565b60068054604080516020601f60026000196101006001881615020190951694909404938401819004810282018101909252828152606093909290918301828280156106095780601f106105de57610100808354040283529160200191610609565b820191906000526020600020905b8154815290600101906020018083116105ec57829003601f168201915b5050505050905090565b6000600160a060020a038316151561062a57600080fd5b336000818152600460209081526040808320600160a060020a03881680855290835292819020869055805186815290519293927f8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925929181900390910190a350600192915050565b600054600160a060020a031633146106a857600080fd5b604080517f70a082310000000000000000000000000000000000000000000000000000000081523060048201529051600091600160a060020a038416916370a0823191602480820192602092909190829003018186803b15801561070b57600080fd5b505afa15801561071f573d6000803e3d6000fd5b505050506040513d602081101561073557600080fd5b505160008054604080517fa9059cbb000000000000000000000000000000000000000000000000000000008152600160a060020a0392831660048201526024810185905290519394509085169263a9059cbb92604480840193602093929083900390910190829087803b1580156107ab57600080fd5b505af11580156107bf573d6000803e3d6000fd5b505050506040513d60208110156107d557600080fd5b50505050565b60055490565b600160a060020a0383166000908152600460209081526040808320338452909152812054610815908363ffffffff610d0416565b600160a060020a0385166000908152600460209081526040808320338452909152902055610844848484610d16565b600160a060020a0384166000818152600460209081526040808320338085529083529281902054815190815290519293927f8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925929181900390910190a35060019392505050565b60008054600160a060020a031633146108c257600080fd5b600160a060020a03821660009081526002602052604090205460ff16151561095d57600160a060020a038216151561093557604080517f08c379a0000000000000000000000000000000000000000000000000000000008152602060048201526000602482015290519081900360640190fd5b50600160a060020a0381166000908152600260205260409020805460ff191660019081179091555b919050565b60085460ff1690565b6000600160a060020a038316151561098257600080fd5b336000908152600460209081526040808320600160a060020a03871684529091529020546109b6908363ffffffff610de516565b336000818152600460209081526040808320600160a060020a0389168085529083529281902085905580519485525191937f8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925929081900390910190a350600192915050565b3360009081526002602052604081205460ff161515610a7557604080517f08c379a0000000000000000000000000000000000000000000000000000000008152602060048201526000602482015290519081900360640190fd5b610a7f8383610dfb565b50600192915050565b600154600160a060020a03163314610a9f57600080fd5b60015460008054604051600160a060020a0393841693909116917f8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e091a3600180546000805473ffffffffffffffffffffffffffffffffffffffff19908116600160a060020a03841617909155169055565b600160a060020a031660009081526003602052604090205490565b60026020526000908152604090205460ff1681565b600054600160a060020a031681565b60078054604080516020601f60026000196101006001881615020190951694909404938401819004810282018101909252828152606093909290918301828280156106095780601f106105de57610100808354040283529160200191610609565b6000600160a060020a0383161515610bc757600080fd5b336000908152600460209081526040808320600160a060020a03871684529091529020546109b6908363ffffffff610d0416565b6000610a7f338484610d16565b60008054600160a060020a03163314610c2057600080fd5b600160a060020a03821660009081526002602052604090205460ff161561095d5750600160a060020a03166000908152600260205260409020805460ff19169055600190565b600160a060020a03918216600090815260046020908152604080832093909416825291909152205490565b600154600160a060020a031681565b600054600160a060020a03163314610cb757600080fd5b6001805473ffffffffffffffffffffffffffffffffffffffff1916600160a060020a0392909216919091179055565b600160a060020a031660009081526002602052604090205460ff1690565b600082821115610d1057fe5b50900390565b600160a060020a0382161515610d2b57600080fd5b600160a060020a038316600090815260036020526040902054610d54908263ffffffff610d0416565b600160a060020a038085166000908152600360205260408082209390935590841681522054610d89908263ffffffff610de516565b600160a060020a0380841660008181526003602090815260409182902094909455805185815290519193928716927fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef92918290030190a3505050565b600082820183811015610df457fe5b9392505050565b600160a060020a0382161515610e1057600080fd5b600554610e23908263ffffffff610de516565b600555600160a060020a038216600090815260036020526040902054610e4f908263ffffffff610de516565b600160a060020a03831660008181526003602090815260408083209490945583518581529351929391927fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef9281900390910190a3505056fea165627a7a72305820de6864ee8b493d12837cc722876e1a9c1f5260df0defd1ac974491703300da7b0029","contractAddress":"0xed5a231ecc0fa775980ad7b86e49872feacd4c8f","cumulativeGasUsed":"6549639","gasUsed":"1209061","confirmations":"4374747"}

http://api.etherscan.io/api?module=contract&action=getabi&address=0xed5a231ecc0fa775980ad7b86e49872feacd4c8f&format=raw

**Comment by roninkaizen** [comment]
?
