### ISSUE TITLE
Error: chequebook init: tx fee (1.42 ether) exceeds the configured cap (1.00 ether)

### ISSUE THREAD

**Issue by JasonYHZ** [goerli/testnet#82]
Due to the congestion of the link, I need to use larger Gasprice but my geeth prompts me this error.

```bash
Error: chequebook init: tx fee (1.42 ether) exceeds the configured cap (1.00 ether)
```

How can I handle this problem? Is there a configuration to be modified

**Comment by matcheydj** [comment]
https://github.com/ChainSafe/ChainBridge/issues/623
