### ISSUE TITLE
the method eth_getWork does not exist/is not available

### ISSUE THREAD

**Issue by chenhaoran0612** [goerli/testnet#89]
I start my geth on testnet , but can not work.

geth --goerli --syncmode fast --datadir /service/ethereum/data --http --http.addr 0.0.0.0 --http.vhosts * --http.api admin,debug,web3,eth,txpool,personal,ethash,miner,net --mine --miner.etherbase 0xA457C350159FFf525E9b7B4F2FE5f40B1B49be16  --cache 2048 --maxpeers 200 --whitelist 10920274=0xfd652086d220d506ae5b7cb80fde97d2f3f7028d346cc7d9d384a83d3d638532

curl http://165.154.4.84:8545 \
    -X POST \
    -H "Content-Type: application/json" \
    -d '{"jsonrpc":"2.0","method":"eth_getWork","params": [],"id":1}'
{"jsonrpc":"2.0","id":1,"error":{"code":-32601,"message":"the method eth_getWork does not exist/is not available"}}

So i trans to offical  rpc . Had the same problem .

curl https://rpc.goerli.mudit.blog \
    -X POST \
    -H "Content-Type: application/json" \
    -d '{"jsonrpc":"2.0","method":"eth_getWork","params": [],"id":1}'
{"jsonrpc":"2.0","id":1,"error":{"code":-32601,"message":"the method eth_getWork does not exist/is not available"}}

**Comment by q9f** [comment]
Hi, Goerli is a proof-of-authority network and cannot be mined, therefore, the `eth_getWork` API is not available.
