### ISSUE TITLE
Goerli Authenticated Faucet to accept other forms of authentication

### ISSUE THREAD

**Issue by arijoon** [goerli/testnet#90]
It would be very useful to accept other forms of authentication such as Github for those of us who do not use twitter or facebook. 
The current system seems very restrictive and similar to a social credit system to allow access to goerli testnet. My usage is very low due to low gas fees (been testing with less than 1ETH for over a month), but about to run out and unable to find any new faucets to gain access. This could force a move back into ropsten

A more accessible form of authentication could be very beneficial, e.g. Github authentication with +1 year old accounts and certain number of commits/contributions

**Comment by TimDaub** [comment]
> It would be very useful to accept other forms of authentication such as Github for those of us who do not use twitter or facebook.

Can't agree more. I thought deploying smart contracts is challenging, but I'm right now mostly challenged with receiving test eth for görli as I neither have FB nor Twitter.

**Comment by q9f** [comment]
We are not operating any faucets. They are community-run. The authenticated faucet is part of the Geth code-base as far as I can tell.

https://github.com/ethereum/go-ethereum/tree/master/cmd/faucet#faucet
