### ISSUE TITLE
Goerli eth is not appearing

### ISSUE THREAD

**Issue by springrider** [goerli/testnet#93]
this transaction shows that I got 6.25 eth from the faucet:
https://goerli.etherscan.io/tx/0x9c144289cf66c034116576501e3bfe1e6f443996f3252aece8b83995eec273dc 

but the eth doesn't show in my account, and etherscan doesn't show that transaction at all:
https://goerli.etherscan.io/address/0x933a3b90fad95278c63d594bca2d574857236930

not sure if everything okay, how could transaction just disappear.

**Comment by q9f** [comment]
It's a glitch! Seems you found a bug in Etherscan! I would encourage to reach out to their support team!

**Comment by springrider** [comment]
> It's a glitch! Seems you found a bug in Etherscan! I would encourage to reach out to their support team!

but the balance also didn't show up in my metamask wallet either, and also imtoken wallet...
